# Generated by Django 4.0.4 on 2022-05-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название продукта', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание продукта', null=True)),
                ('places', models.CharField(blank=True, help_text='places', max_length=100, null=True)),
                ('imgsrc', models.ImageField(help_text='Фотография продукта', upload_to='product_image')),
                ('email', models.CharField(blank=True, help_text='Почта', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, help_text='Телефоный номер', max_length=100, null=True)),
                ('cretated', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, help_text='Status Product', verbose_name='staff status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='categories.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.location')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AcceptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(limit_choices_to={'status': False}, on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='orders.order')),
            ],
            options={
                'verbose_name': 'Принимать заказ',
                'verbose_name_plural': 'Принимать заказы',
            },
        ),
    ]
