# Generated by Django 4.0.4 on 2022-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_image',
            field=models.ImageField(default=1, upload_to='order_image/'),
            preserve_default=False,
        ),
    ]
