# Generated by Django 4.0.4 on 2022-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_acceptorder_created_alter_acceptorder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorder',
            name='order',
            field=models.OneToOneField(limit_choices_to={'status': False}, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
