# Generated by Django 4.0.4 on 2022-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_acceptorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imgsrc',
            field=models.FileField(help_text='Фотография продукта', upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_image',
            field=models.FileField(upload_to='order_image/'),
        ),
    ]
