# Generated by Django 3.2.7 on 2022-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220426_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='orders.order', unique=True),
        ),
    ]
