# Generated by Django 3.2.7 on 2022-04-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_acceptorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptorder',
            name='id',
        ),
        migrations.AddField(
            model_name='acceptorder',
            name='order_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order'),
            preserve_default=False,
        ),
    ]
