# Generated by Django 4.0.4 on 2022-11-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_acceptorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, help_text='Status Product'),
        ),
    ]
