# Generated by Django 3.2.7 on 2022-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_acceptorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptorder',
            name='order_ptr',
        ),
        migrations.AddField(
            model_name='acceptorder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
