# Generated by Django 3.2.7 on 2022-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_acceptorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, help_text='Status Product', verbose_name='staff status'),
        ),
    ]
