insert into categories_category (content) values ('Авиакасса');
insert into categories_category (content) values ('Работа разнорабочий');
insert into categories_category (content) values ('Сдаю комнату / жилье');
insert into categories_category (content) values ('Сниму комнату/ квартиру');
insert into categories_category (content) values ('Мейманкана/Хостел');
insert into categories_category (content) values ('Агентство недвижимости');
insert into categories_category (content) values ('Продаю / Куплю');
insert into categories_category (content) values ('Медицина');
insert into categories_category (content) values ('Грузоперевозки');
insert into categories_category (content) values ('Чайхана');
insert into categories_category (content) values ('Той кана');
insert into categories_category (content) values ('Бильярдный Клуб');
insert into categories_category (content) values ('Обучение');
insert into categories_category (content) values ('Красота и здоровье');
insert into categories_category (content) values ('Транспорт');
insert into categories_category (content) values ('Автосервис');
insert into categories_category (content) values ('Авто-мото');
insert into categories_category (content) values ('Прокат костюм');
insert into categories_category (content) values ('Мал базар');
insert into categories_category (content) values ('Фото видео кызматары');
insert into categories_category (content) values ('Парихмакерская');
insert into categories_category (content) values ('Эт сатылат');
insert into categories_category (content) values ('Услуги');