# Generated by Django 3.2.7 on 2022-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
    ]
