# Generated by Django 4.0.4 on 2022-11-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_location_location_self'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
