# Generated by Django 4.0.4 on 2022-08-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cateory',
            new_name='user_cateory',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='user_location',
        ),
    ]
