# Generated by Django 4.0.4 on 2022-05-17 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only 10 digits NTC or NCELL numbers allowed.', regex='^98\\d{8}$')])),
                ('validated', models.BooleanField(default=False, help_text='Ensure Mobile Verified Badge')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_count', models.PositiveSmallIntegerField(default=0, help_text='Count of OTP sent.')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only 10 digits NTC or NCELL numbers allowed.', regex='^98\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
