# Generated by Django 4.0.4 on 2022-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_cateory_user_cateory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cateory',
            new_name='user_category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='user_location',
        ),
    ]
