# Generated by Django 4.0.4 on 2022-08-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_cateory_user_user_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_or_employee',
            field=models.CharField(blank=True, choices=[('Заказчик', 'Заказчик'), ('Работник', 'Работник')], default='Работник', max_length=255, null=True),
        ),
    ]
