# Generated by Django 4.0.4 on 2022-10-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0005_user_customer_or_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.location'),
        ),
    ]
