# Generated by Django 4.0.4 on 2022-06-12 11:15

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.upload_path),
        ),
    ]
